const float LEEFY_MOVE_SPEED = 5.0f;
const float LEEFY_FALL_SPEED = 250.0f; 
const float DAMPING = 0.87f;
const int DISTANCE_BETWEEN_COINS_MIN = 100;
const int DISTANCE_BETWEEN_COINS_MAX = 400;

const int DISTANCE_BETWEEN_BRANCHES_MIN = 250;
const int DISTANCE_BETWEEN_BRANCHES_MAX = 400;